(defpackage :lice
  (:use :cl))

#+sbcl (require :sb-posix)

(require 'cl-ncurses)
(require 'cl-ppcre)

(labels ((cnl (file)
	   (load (compile-file file))))
  (cnl "wrappers")
  (cnl "global")
  (cnl "custom")
  (cnl "commands")
  (cnl "keymap")
  (cnl "major-mode")
  (cnl "buffer")
  (cnl "subr")
  (cnl "files")
  (cnl "intervals")
  (cnl "textprop")
  (cnl "editfns")
  (cnl "window")
  (cnl "frame")
  (cnl "tty-render")
  (cnl "syntax")
  (cnl "debugger")
  (cnl "recursive-edit")
  (cnl "wm")
  (cnl "minibuffer")
  (cnl "simple")
  (cnl "undo")
  (cnl "indent")
  (cnl "lisp-mode")
  (cnl "search")
  (cnl "help")
  (cnl "debug")
  (cnl "subprocesses")
  (cnl "lisp-indent")
  (cnl "input")
  (cnl "main")

  (cnl "casefiddle")
  (cnl "paragraphs")

  (cnl "text-mode")
  (cnl "doctor")
)
