(cl:defpackage "LICE"
  (:use :cl)
   (:export
    ;;; Base symbols. In Emacs these are implemented in C
    ;; abbrev.c
    #:make-abbrev-table
    #:clear-abbrev-table
    #:define-abbrev
    #:define-global-abbrev
    #:define-mode-abbrev
    #:abbrev-expansion
    #:abbrev-symbol
    #:expand-abbrev
    #:unexpand-abbrev
    #:insert-abbrev-table-description
    #:define-abbrev-table
    ;; alloc.c
    #:cons
    #:list
    #:vector
    #:make-byte-code
    #:make-list
    #:make-vector
    #:make-char-table
    #:make-string
    #:make-bool-vector
    #:make-symbol
    #:make-marker
    #:purecopy
    #:garbage-collect
    #:memory-limit
    #:memory-use-counts
    #:gc-status
    ;; buffer.c
    #:buffer-live-p
    #:buffer-list
    #:get-buffer
    #:get-file-buffer
    #:get-buffer-create
    #:make-indirect-buffer
    #:generate-new-buffer-name
    #:buffer-name
    #:buffer-number
    #:buffer-file-name
    #:buffer-base-buffer
    #:buffer-local-value
    #:buffer-local-variables
    #:buffer-modified-p
    #:set-buffer-modified-p
    #:buffer-modified-tick
    #:buffer-chars-modified-tick
    #:rename-buffer
    #:other-buffer
    #:buffer-enable-undo
    #:kill-buffer
    #:set-buffer-major-mode
    #:switch-to-buffer
    #:pop-to-buffer
    #:current-buffer
    #:set-buffer
    #:barf-if-buffer-read-only
    #:bury-buffer
    #:erase-buffer
    #:set-buffer-multibyte
    #:kill-all-local-variables
    #:overlayp
    #:make-overlay
    #:delete-overlay
    #:move-overlay
    #:overlay-start
    #:overlay-end
    #:overlay-buffer
    #:overlay-properties
    #:overlays-at
    #:overlays-in
    #:next-overlay-change
    #:previous-overlay-change
    #:overlay-recenter
    #:overlay-lists
    #:overlay-get
    #:overlay-put
    #:restore-buffer-modified-p
    ;; bytecode.c
    #:byte-code
    ;; callint.c
    #:interactive
    #:call-interactively
    #:prefix-numeric-value
    ;; callproc.c
    #:call-process
    #:getenv-internal
    #:call-process-region
    ;; casefiddle.c
    #:upcase
    #:downcase
    #:capitalize
    #:upcase-initials
    #:upcase-region
    #:downcase-region
    #:capitalize-region
    #:upcase-initials-region
    #:upcase-word
    #:downcase-word
    #:capitalize-word
    ;; casetab.c
    #:case-table-p
    #:current-case-table
    #:standard-case-table
    #:set-case-table
    #:set-standard-case-table
    ;; category.c
    #:make-category-set
    #:define-category
    #:category-docstring
    #:get-unused-category
    #:category-table-p
    #:category-table
    #:standard-category-table
    #:copy-category-table
    #:make-category-table
    #:set-category-table
    #:char-category-set
    #:category-set-mnemonics
    #:modify-category-entry
    ;; ccl.c
    #:ccl-program-p
    #:ccl-execute
    #:ccl-execute-on-string
    #:register-ccl-program
    #:register-code-conversion-map
    ;; charset.c
    #:define-charset
    #:generic-character-list
    #:get-unused-iso-final-char
    #:declare-equiv-charset
    #:find-charset-region
    #:find-charset-string
    #:make-char-internal
    #:split-char
    #:char-charset
    #:charset-after
    #:iso-charset
    #:char-valid-p
    #:unibyte-char-to-multibyte
    #:multibyte-char-to-unibyte
    #:char-bytes
    #:char-width
    #:string-width
    #:char-direction
    #:string
    #:setup-special-charsets
    ;; cmds.c
    #:forward-point
    #:forward-char
    #:backward-char
    #:forward-line
    #:beginning-of-line
    #:end-of-line
    #:delete-char
    #:delete-backward-char
    #:self-insert-command
    ;; coding.c
    #:coding-system-p
    #:read-coding-system
    #:read-non-nil-coding-system
    #:check-coding-system
    #:detect-coding-region
    #:detect-coding-string
    #:find-coding-systems-region-internal
    #:unencodable-char-position
    #:decode-coding-region
    #:encode-coding-region
    #:decode-coding-string
    #:encode-coding-string
    #:decode-sjis-char
    #:encode-sjis-char
    #:decode-big5-char
    #:encode-big5-char
    #:set-terminal-coding-system-internal
    #:set-safe-terminal-coding-system-internal
    #:terminal-coding-system
    #:set-keyboard-coding-system-internal
    #:keyboard-coding-system
    #:find-operation-coding-system
    #:update-coding-systems-internal
    #:set-coding-priority-internal
    #:define-coding-system-internal
    ;; composite.c
    #:compose-region-internal
    #:compose-string-internal
    #:find-composition-internal
    ;; data.c
    #:indirect-variable
    #:interactive-form
    #:eq
    #:null
    #:type-of
    #:listp
    #:nlistp
    #:consp
    #:atom
    #:integerp
    #:integer-or-marker-p
    #:numberp
    #:number-or-marker-p
    #:floatp
    #:natnump
    #:symbolp
    #:keywordp
    #:stringp
    #:multibyte-string-p
    #:vectorp
    #:char-table-p
    #:vector-or-char-table-p
    #:bool-vector-p
    #:arrayp
    #:sequencep
    #:bufferp
    #:markerp
    #:subrp
    #:byte-code-function-p
    #:char-or-string-p
    #:car
    #:cdr
    #:car-safe
    #:cdr-safe
    #:setcar
    #:setcdr
    #:symbol-function
    #:indirect-function
    #:symbol-plist
    #:symbol-name
    #:makunbound
    #:fmakunbound
    #:boundp
    #:fboundp
    #:fset
    #:defalias
    #:setplist
    #:symbol-value
    #:set
    #:default-boundp
    #:default-value
    #:set-default
    #:setq-default
    #:make-variable-buffer-local
    #:make-local-variable
    #:kill-local-variable
    #:make-variable-frame-local
    #:local-variable-p
    #:local-variable-if-set-p
    #:variable-binding-locus
    #:aref
    #:aset
    #:number-to-string
    #:string-to-number
    #:eqlsign
    #:lss
    #:gtr
    #:leq
    #:geq
    #:neq
    #:zerop
    #:plus
    #:minus
    #:times
    #:quo
    #:rem
    #:mod
    #:max
    #:min
    #:logand
    #:logior
    #:logxor
    #:lsh
    #:ash
    #:add1
    #:sub1
    #:lognot
    #:byteorder
    #:subr-arity
    #:subr-name
    ;; dired.c
    #:directory-files
    #:directory-files-and-attributes
    #:file-name-completion
    #:file-name-all-versions
    #:file-version-limit
    #:file-name-all-completions
    #:file-attributes
    #:file-attributes-lessp
    ;; dispnew.c
    #:redraw-frame
    #:redraw-display
    #:frame-or-buffer-changed-p
    #:open-termscript
    #:ding
    #:redisplay
    #:sleep-for
    #:send-string-to-terminal
    #:internal-show-cursor
    #:internal-show-cursor-p
    #:dump-redisplay-history
    ;; doc.c
    #:documentation
    #:documentation-property
    #:snarf-documentation
    #:substitute-command-keys
    ;; dosfns.c
    #:int86
    #:dos-memget
    #:dos-memput
    #:msdos-mouse-init
    #:msdos-mouse-enable
    #:msdos-set-keyboard
    #:insert-startup-screen
    #:msdos-mouse-disable
    #:file-system-info
    #:msdos-mouse-p
    ;; editfns.c
    #:propertize
    #:char-equal
    #:goto-char
    #:string-to-char
    #:char-to-string
    #:buffer-substring
    #:buffer-substring-no-properties
    #:buffer-string
    #:point-marker
    #:mark-marker
    #:point
    #:region-beginning
    #:region-end
    #:field-beginning
    #:field-end
    #:field-string
    #:field-string-no-properties
    #:delete-field
    #:constrain-to-field
    #:line-beginning-position
    #:line-end-position
    #:mark
    #:set-mark
    #:save-excursion
    #:save-current-buffer
    #:bufsize
    #:point-max
    #:point-min
    #:point-min-marker
    #:point-max-marker
    #:gap-position
    #:gap-size
    #:position-bytes
    #:byte-to-position
    #:bobp
    #:eobp
    #:bolp
    #:eolp
    #:following-char
    #:previous-char
    #:char-after
    #:char-before
    #:insert
    #:insert-before-markers
    #:insert-and-inherit
    #:insert-and-inherit-before-markers
    #:insert-char
    #:user-login-name
    #:user-real-login-name
    #:user-uid
    #:user-real-uid
    #:user-full-name
    #:emacs-pid
    #:current-time
    #:get-internal-run-time
    #:format-time-string
    #:float-time
    #:decode-time
    #:encode-time
    #:current-time-string
    #:current-time-zone
    #:set-time-zone-rule
    #:system-name
    #:message
    #:message-box
    #:message-or-box
    #:current-message
    #:format
    #:insert-buffer-substring
    #:compare-buffer-substrings
    #:subst-char-in-region
    #:translate-region-internal
    #:delete-region
    #:delete-and-extract-region
    #:widen
    #:narrow-to-region
    #:save-restriction
    #:transpose-regions
    ;; emacs.c
    #:dump-emacs-data
    #:dump-emacs
    #:kill-emacs
    #:invocation-name
    #:invocation-directory
    ;; eval.c
    #:or
    #:and
    #:if
    #:cond
    #:progn
    #:prog1
    #:prog2
    #:setq
    #:quote
    #:function
    #:defun
    #:defmacro
    #:defvar
    #:defvaralias
    #:defconst
    #:user-variable-p
    #:let
    #:letX
    #:while
    #:macroexpand
    #:catch
    #:throw
    #:unwind-protect
    #:condition-case
    #:signal
    #:interactive-p
    #:called-interactively-p
    #:commandp
    #:autoload
    #:eval
    #:apply
    #:funcall
    #:run-hooks
    #:run-hook-with-args
    #:run-hook-with-args-until-success
    #:run-hook-with-args-until-failure
    #:fetch-bytecode
    #:backtrace-debug
    #:backtrace
    #:backtrace-frame
    ;; fileio.c
    #:find-file-name-handler
    #:file-name-directory
    #:file-name-nondirectory
    #:unhandled-file-name-directory
    #:file-name-as-directory
    #:directory-file-name
    #:make-temp-name
    #:expand-file-name
    #:substitute-in-file-name
    #:copy-file
    #:make-directory-internal
    #:delete-directory
    #:delete-file
    #:rename-file
    #:add-name-to-file
    #:make-symbolic-link
    #:define-logical-name
    #:sysnetunam
    #:file-name-absolute-p
    #:file-exists-p
    #:file-executable-p
    #:file-readable-p
    #:file-writable-p
    #:access-file
    #:file-symlink-p
    #:file-directory-p
    #:file-accessible-directory-p
    #:file-regular-p
    #:file-modes
    #:set-file-modes
    #:set-file-times
    #:set-default-file-modes
    #:default-file-modes
    #:file-newer-than-file-p
    #:insert-file-contents
    #:write-region
    #:car-less-than-car
    #:verify-visited-file-modtime
    #:clear-visited-file-modtime
    #:visited-file-modtime
    #:set-visited-file-modtime
    #:do-auto-save
    #:set-buffer-auto-saved
    #:clear-buffer-auto-save-failure
    #:recent-auto-save-p
    #:read-file-name-internal
    #:read-file-name
    #:next-read-file-uses-dialog-p
    #:unix-sync
    ;; filelock.c
    #:unlock-buffer
    #:lock-buffer
    #:file-locked-p
    ;; floatfns.c
    #:acos
    #:asin
    #:atan
    #:cos
    #:sin
    #:tan
    #:acosh
    #:asinh
    #:atanh
    #:cosh
    #:sinh
    #:tanh
    #:bessel-y0
    #:bessel-y1
    #:bessel-yn
    #:bessel-j0
    #:bessel-j1
    #:bessel-jn
    #:erf
    #:erfc
    #:log-gamma
    #:cube-root
    #:fceiling
    #:ffloor
    #:fround
    #:ftruncate
    #:exp
    #:expt
    #:log
    #:log10
    #:sqrt
    #:abs
    #:float
    #:logb
    #:ceiling
    #:floor
    #:round
    #:truncate
    ;; fns.c
    #:sxhash
    #:make-hash-table
    #:copy-hash-table
    #:hash-table-count
    #:hash-table-rehash-size
    #:hash-table-rehash-threshold
    #:hash-table-size
    #:hash-table-test
    #:hash-table-weakness
    #:hash-table-p
    #:clrhash
    #:gethash
    #:puthash
    #:remhash
    #:maphash
    #:define-hash-table-test
    #:identity
    #:random
    #:length
    #:safe-length
    #:string-bytes
    #:string-equal
    #:compare-strings
    #:string-lessp
    #:append
    #:concat
    #:vconcat
    #:copy-sequence
    #:string-make-multibyte
    #:string-make-unibyte
    #:string-as-multibyte
    #:string-as-unibyte
    #:string-to-multibyte
    #:copy-alist
    #:substring
    #:substring-no-properties
    #:nthcdr
    #:nth
    #:elt
    #:member
    #:memq
    #:memql
    #:assq
    #:assoc
    #:rassq
    #:rassoc
    #:delq
    #:delete
    #:nreverse
    #:reverse
    #:sort
    #:plist-get
    #:get
    #:plist-put
    #:put
    #:lax-plist-get
    #:lax-plist-put
    #:eql
    #:equal
    #:equal-including-properties
    #:fillarray
    #:clear-string
    #:char-table-subtype
    #:char-table-parent
    #:set-char-table-parent
    #:char-table-extra-slot
    #:set-char-table-extra-slot
    #:char-table-range
    #:set-char-table-range
    #:set-char-table-default
    #:optimize-char-table
    #:map-char-table
    #:nconc
    #:mapcar
    #:mapc
    #:mapconcat
    #:y-or-n-p
    #:yes-or-no-p
    #:load-average
    #:featurep
    #:require
    #:provide
    #:plist-member
    #:widget-put
    #:widget-get
    #:widget-apply
    #:base64-encode-region
    #:base64-decode-region
    #:base64-encode-string
    #:base64-decode-string
    #:md5
    #:locale-info
    ;; fontset.c
    #:query-fontset
    #:new-fontset
    #:set-fontset-font
    #:font-info
    #:internal-char-font
    #:fontset-info
    #:fontset-font
    #:fontset-list
    #:set-overriding-fontspec-internal
    ;; frame.c
    #:active-minibuffer-window
    #:framep
    #:frame-live-p
    #:make-terminal-frame
    #:handle-switch-frame
    #:select-frame
    #:selected-frame
    #:window-frame
    #:frame-root-window
    #:frame-first-window
    #:frame-selected-window
    #:set-frame-selected-window
    #:frame-list
    #:next-frame
    #:previous-frame
    #:delete-frame
    #:mouse-position
    #:mouse-pixel-position
    #:set-mouse-position
    #:set-mouse-pixel-position
    #:frame-configuration
    #:restore-frame-configuration
    #:make-frame-visible
    #:make-frame-invisible
    #:iconify-frame
    #:frame-visible-p
    #:visible-frame-list
    #:raise-frame
    #:lower-frame
    #:redirect-frame-focus
    #:frame-focus
    #:frame-parameters
    #:frame-parameter
    #:modify-frame-parameters
    #:frame-char-height
    #:frame-char-width
    #:frame-pixel-height
    #:frame-pixel-width
    #:set-frame-height
    #:set-frame-width
    #:set-frame-size
    #:set-frame-position
    #:x-get-resource
    #:x-parse-geometry
    ;; fringe.c
    #:destroy-fringe-bitmap
    #:define-fringe-bitmap
    #:fringe-bitmaps-at-pos
    #:set-fringe-bitmap-face
    ;; image.c
    #:init-image-library
    #:clear-image-cache
    #:image-size
    #:image-mask-p
    #:image-extension-data
    #:imagep
    #:lookup-image
    ;; indent.c
    #:current-indentation
    #:indent-to
    #:current-column
    #:move-to-column
    #:vertical-motion
    #:compute-motion
    ;; insdel.c
    #:combine-after-change-execute
    ;; keyboard.c
    #:current-idle-time
    #:event-convert-list
    #:read-key-sequence
    #:read-key-sequence-vector
    #:recursive-edit
    #:track-mouse
    #:input-pending-p
    #:command-execute
    #:recent-keys
    #:this-command-keys
    #:this-command-keys-vector
    #:this-single-command-keys
    #:this-single-command-raw-keys
    #:reset-this-command-lengths
    #:clear-this-command-keys
    #:suspend-emacs
    #:abort-recursive-edit
    #:exit-recursive-edit
    #:recursion-depth
    #:top-level
    #:discard-input
    #:open-dribble-file
    #:set-input-mode
    #:current-input-mode
    #:execute-extended-command
    #:posn-at-point
    #:posn-at-x-y
    ;; keymap.c
    #:keymapp
    #:keymap-parent
    #:keymap-prompt
    #:set-keymap-parent
    #:make-keymap
    #:make-sparse-keymap
    #:map-keymap
    #:copy-keymap
    #:command-remapping
    #:key-binding
    #:local-key-binding
    #:global-key-binding
    #:minor-mode-key-binding
    #:define-key
    #:lookup-key
    #:define-prefix-command
    #:use-global-map
    #:use-local-map
    #:current-local-map
    #:current-global-map
    #:current-minor-mode-maps
    #:current-active-maps
    #:accessible-keymaps
    #:key-description
    #:describe-vector
    #:single-key-description
    #:text-char-description
    #:where-is-internal
    #:describe-buffer-bindings
    #:apropos-internal
    ;; lread.c
    #:ame
    #:read
    #:read-from-string
    #:intern
    #:intern-soft
    #:unintern
    #:get-load-suffixes
    #:load
    #:eval-buffer
    #:eval-region
    #:read-char
    #:read-char-exclusive
    #:read-event
    #:get-file-char
    #:mapatoms
    #:locate-file-internal
    ;; mac.c
    #:mac-coerce-ae-data
    #:mac-get-preference
    #:mac-code-convert-string
    #:mac-process-hi-command
    #:mac-set-file-creator
    #:mac-set-file-type
    #:mac-get-file-creator
    #:mac-get-file-type
    #:do-applescript
    #:mac-file-name-to-posix
    #:posix-file-name-to-mac
    ;; macfns.c
    #:x-change-window-property
    #:x-delete-window-property
    #:x-window-property
    #:xw-display-color-p
    #:x-display-grayscale-p
    #:xw-color-defined-p
    #:xw-color-values
    #:x-server-max-request-size
    #:x-server-vendor
    #:x-server-version
    #:x-display-pixel-width
    #:x-display-pixel-height
    #:x-display-mm-width
    #:x-display-mm-height
    #:x-display-screens
    #:x-display-planes
    #:x-display-color-cells
    #:x-display-visual-class
    #:x-display-backing-store
    #:x-display-save-under
    #:x-create-frame
    #:x-open-connection
    #:x-close-connection
    #:x-display-list
    #:x-synchronize
    #:x-focus-frame
    #:x-show-tip
    #:x-hide-tip
    #:x-file-dialog
    #:mac-clear-font-name-table
    #:mac-set-font-panel-visibility
    #:mac-atsu-font-face-attributes
    ;; macmenu.c
    #:x-popup-menu
    #:menu-or-popup-active-p
    #:x-popup-dialog
    ;; macros.c
    #:start-kbd-macro
    #:end-kbd-macro
    #:call-last-kbd-macro
    #:execute-kbd-macro
    #:cancel-kbd-macro-events
    #:store-kbd-macro-event
    ;; macselect.c
    #:x-get-selection-internal
    #:x-own-selection-internal
    #:x-disown-selection-internal
    #:x-selection-owner-p
    #:x-selection-exists-p
    #:mac-process-deferred-apple-events
    #:mac-cleanup-expired-apple-events
    #:mac-resume-apple-event
    #:mac-ae-set-reply-parameter
    ;; marker.c
    #:marker-position
    #:marker-buffer
    #:set-marker
    #:copy-marker
    #:marker-insertion-type
    #:set-marker-insertion-type
    #:buffer-has-markers-at
    ;; minibuf.c
    #:set-minibuffer-window
    #:read-from-minibuffer
    #:eval-minibuffer
    #:read-minibuffer
    #:read-string
    #:read-command
    #:read-variable
    #:internal-complete-buffer
    #:read-buffer
    #:read-no-blanks-input
    #:minibuffer-depth
    #:minibuffer-prompt
    #:minibufferp
    #:minibuffer-prompt-end
    #:minibuffer-contents
    #:minibuffer-contents-no-properties
    #:minibuffer-completion-contents
    #:delete-minibuffer-contents
    #:try-completion
    #:all-completions
    #:test-completion
    #:assoc-string
    #:completing-read
    #:minibuffer-complete
    #:minibuffer-complete-word
    #:minibuffer-complete-and-exit
    #:display-completion-list
    #:minibuffer-completion-help
    #:self-insert-and-exit
    #:exit-minibuffer
    #:minibuffer-message
    ;; msdos.c
    #:recent-doskeys
    #:msdos-long-file-names
    #:msdos-downcase-filename
    #:msdos-remember-default-colors
    #:msdos-set-mouse-buttons
    ;; print.c
    #:prin1
    #:prin1-to-string
    #:error-message-string
    #:princ
    #:print
    #:terpri
    #:write-char
    #:external-debugging-output
    #:redirect-debugging-output
    #:with-output-to-temp-buffer
    ;; process.c
    #:processp
    #:get-process
    #:get-buffer-process
    #:delete-process
    #:process-status
    #:process-exit-status
    #:process-id
    #:process-name
    #:process-tty-name
    #:process-command
    #:set-process-buffer
    #:process-buffer
    #:process-mark
    #:set-process-filter
    #:process-filter
    #:set-process-sentinel
    #:process-sentinel
    #:set-process-window-size
    #:set-process-inherit-coding-system-flag
    #:process-inherit-coding-system-flag
    #:set-process-query-on-exit-flag
    #:process-query-on-exit-flag
    #:process-contact
    #:process-plist
    #:set-process-plist
    #:list-processes
    #:process-list
    #:start-process
    #:set-network-process-option
    #:make-network-process
    #:format-network-address
    #:network-interface-list
    #:network-interface-info
    #:process-datagram-address
    #:set-process-datagram-address
    #:accept-process-output
    #:process-send-region
    #:process-send-string
    #:interrupt-process
    #:kill-process
    #:quit-process
    #:stop-process
    #:continue-process
    #:process-running-child-p
    #:process-send-eof
    #:signal-process
    #:waiting-for-user-input-p
    #:process-connection
    #:set-process-coding-system
    #:process-coding-system
    #:set-process-filter-multibyte
    #:process-filter-multibyte-p
    #:get-buffer-process
    #:process-inherit-coding-system-flag
    ;; search.c
    #:looking-at
    #:posix-looking-at
    #:string-match
    #:posix-string-match
    #:search-forward
    #:search-backward
    #:word-search-forward
    #:word-search-backward
    #:re-search-forward
    #:re-search-backward
    #:posix-search-forward
    #:posix-search-backward
    #:replace-match
    #:match-beginning
    #:match-end
    #:match-data
    #:set-match-data
    #:regexp-quote
    ;; sound.c
    #:play-sound-internal
    ;; sunfns.c
    #:un-window-init
    #:it-for-millisecs
    #:leep-for-millisecs
    #:pdate-display
    #:un-change-cursor-icon
    #:un-set-selection
    #:un-get-selection
    #:un-menu-internal
    ;; syntax.c
    #:syntax-table-p
    #:syntax-table
    #:standard-syntax-table
    #:copy-syntax-table
    #:set-syntax-table
    #:char-syntax
    #:matching-paren
    #:string-to-syntax
    #:modify-syntax-entry
    #:internal-describe-syntax-value
    #:forward-word
    #:skip-chars-forward
    #:skip-chars-backward
    #:skip-syntax-forward
    #:skip-syntax-backward
    #:forward-comment
    #:scan-lists
    #:scan-sexps
    #:backward-prefix-chars
    #:parse-partial-sexp
    ;; term.c
    #:tty-display-color-p
    #:tty-display-color-cells
    #:tty-no-underline
    ;; textprop.c
    #:text-properties-at
    #:get-text-property
    #:get-char-property
    #:get-char-property-and-overlay
    #:next-char-property-change
    #:previous-char-property-change
    #:next-single-char-property-change
    #:previous-single-char-property-change
    #:next-property-change
    #:next-single-property-change
    #:previous-property-change
    #:previous-single-property-change
    #:add-text-properties
    #:put-text-property
    #:set-text-properties
    #:remove-text-properties
    #:remove-list-of-text-properties
    #:text-property-any
    #:text-property-not-all
    #:erase-text-properties
    #:copy-text-properties
    ;; undo.c
    #:primitive-undo
    #:undo-boundary
    ;; w16select.c
    #:w16-set-clipboard-data
    #:w16-get-clipboard-data
    #:x-selection-exists-p
    ;; w32console.c
    #:set-screen-color
    #:set-cursor-size
    #:set-message-beep
    ;; w32fns.c
    #:x-change-window-property
    #:x-delete-window-property
    #:x-window-property
    #:xw-display-color-p
    #:x-display-grayscale-p
    #:xw-color-defined-p
    #:xw-color-values
    #:x-server-max-request-size
    #:x-server-vendor
    #:x-server-version
    #:x-display-pixel-width
    #:x-display-pixel-height
    #:x-display-mm-width
    #:x-display-mm-height
    #:x-display-screens
    #:x-display-planes
    #:x-display-color-cells
    #:x-display-visual-class
    #:x-display-backing-store
    #:x-display-save-under
    #:x-create-frame
    #:x-open-connection
    #:x-close-connection
    #:x-display-list
    #:x-synchronize
    #:w32-focus-frame
    #:w32-select-font
    #:w32-define-rgb-color
    #:w32-default-color-map
    #:w32-load-color-file
    #:w32-send-sys-command
    #:w32-shell-execute
    #:w32-register-hot-key
    #:w32-unregister-hot-key
    #:w32-registered-hot-keys
    #:w32-reconstruct-hot-key
    #:w32-toggle-lock-key
    #:w32-window-exists-p
    #:w32-find-bdf-fonts
    #:file-system-info
    #:default-printer-name
    #:x-show-tip
    #:x-hide-tip
    #:x-file-dialog
    ;; w32menu.c
    #:x-popup-menu
    #:menu-or-popup-active-p
    #:x-popup-dialog
    #:w32-has-winsock
    #:w32-unload-winsock
    #:w32-short-file-name
    #:w32-long-file-name
    #:w32-set-process-priority
    #:w32-get-locale-info
    #:w32-get-current-locale-id
    #:w32-get-default-locale-id
    #:w32-get-valid-locale-ids
    #:w32-set-current-locale
    #:w32-get-console-codepage
    #:w32-set-console-codepage
    #:w32-get-console-output-codepage
    #:w32-set-console-output-codepage
    #:w32-get-valid-codepages
    #:w32-get-codepage-charset
    #:w32-get-valid-keyboard-layouts
    #:w32-get-keyboard-layout
    #:w32-set-keyboard-layout
    ;; w32select.c
    #:w32-set-clipboard-data
    #:w32-get-clipboard-data
    #:x-selection-exists-p
    ;; window.c
    #:selected-window
    #:minibuffer-window
    #:window-minibuffer-p
    #:windowp
    #:window-live-p
    #:pos-visible-in-window-p
    #:window-line-height
    #:window-buffer
    #:window-height
    #:window-width
    #:window-hscroll
    #:set-window-hscroll
    #:window-redisplay-end-trigger
    #:set-window-redisplay-end-trigger
    #:window-edges
    #:window-pixel-edges
    #:window-inside-edges
    #:window-inside-pixel-edges
    #:coordinates-in-window-p
    #:window-at
    #:window-point
    #:window-start
    #:window-end
    #:set-window-point
    #:set-window-start
    #:window-dedicated-p
    #:set-window-dedicated-p
    #:window-display-table
    #:set-window-display-table
    #:next-window
    #:previous-window
    #:other-window
    #:get-lru-window
    #:get-largest-window
    #:get-buffer-window
    #:delete-other-windows
    #:delete-windows-on
    #:replace-buffer-in-windows
    #:delete-window
    #:set-window-buffer
    #:select-window
    #:special-display-p
    #:same-window-p
    #:display-buffer
    #:force-window-update
    #:split-window
    #:enlarge-window
    #:shrink-window
    #:adjust-window-trailing-edge
    #:scroll-up
    #:scroll-down
    #:scroll-left
    #:scroll-right
    #:other-window-for-scrolling
    #:scroll-other-window
    #:minibuffer-selected-window
    #:recenter
    #:window-text-height
    #:move-to-window-line
    #:window-configuration-p
    #:window-configuration-frame
    #:set-window-configuration
    #:current-window-configuration
    #:save-window-excursion
    #:window-tree
    #:set-window-margins
    #:window-margins
    #:set-window-fringes
    #:window-fringes
    #:set-window-scroll-bars
    #:window-scroll-bars
    #:window-vscroll
    #:set-window-vscroll
    #:compare-window-configurations
    #:window-list
    ;; xdisp.c
    #:dump-frame-glyph-matrix
    #:dump-glyph-matrix
    #:dump-glyph-row
    #:dump-tool-bar-row
    #:trace-redisplay
    #:trace-to-stderr
    #:tool-bar-lines-needed
    #:lookup-image-map
    #:format-mode-line
    ;; xfaces.c
    #:internal-make-lisp-face
    #:internal-lisp-face-p
    #:internal-set-lisp-face-attribute
    #:internal-set-lisp-face-attribute-from-resource
    #:color-gray-p
    #:color-supported-p
    #:face-attribute-relative-p
    #:merge-face-attribute
    #:internal-get-lisp-face-attribute
    #:internal-lisp-face-attribute-values
    #:internal-lisp-face-equal-p
    #:internal-lisp-face-empty-p
    #:internal-copy-lisp-face
    #:internal-merge-in-global-face
    #:face-font
    #:frame-face-alist
    #:display-supports-face-attributes-p
    #:color-distance
    #:internal-set-font-selection-order
    #:internal-set-alternative-font-family-alist
    #:internal-set-alternative-font-registry-alist
    #:face-attributes-as-vector
    #:dump-face
    #:show-face-resources
    #:clear-face-cache
    #:tty-suppress-bold-inverse-default-colors
    #:dump-colors
    #:bitmap-spec-p
    #:x-list-fonts
    #:internal-face-x-get-resource
    #:x-family-fonts
    #:x-font-family-list
    ;; xfns.c
    #:x-change-window-property
    #:x-delete-window-property
    #:x-window-property
    #:xw-display-color-p
    #:x-display-grayscale-p
    #:xw-color-defined-p
    #:xw-color-values
    #:x-server-max-request-size
    #:x-server-vendor
    #:x-server-version
    #:x-display-pixel-width
    #:x-display-pixel-height
    #:x-display-mm-width
    #:x-display-mm-height
    #:x-display-screens
    #:x-display-planes
    #:x-display-color-cells
    #:x-display-visual-class
    #:x-display-backing-store
    #:x-display-save-under
    #:x-create-frame
    #:x-open-connection
    #:x-close-connection
    #:x-display-list
    #:x-synchronize
    #:x-focus-frame
    #:x-backspace-delete-keys-p
    #:x-show-tip
    #:x-hide-tip
    #:x-uses-old-gtk-dialog
    #:x-file-dialog
    ;; xmenu.c
    #:x-popup-menu
    #:menu-or-popup-active-p
    #:menu-bar-open
    #:x-popup-dialog
    ;; xselect.c
    #:x-get-selection-internal
    #:x-own-selection-internal
    #:x-disown-selection-internal
    #:x-selection-owner-p
    #:x-selection-exists-p
    #:x-get-cut-buffer-internal
    #:x-store-cut-buffer-internal
    #:x-rotate-cut-buffers-internal
    #:x-get-atom-name
    #:x-send-client-message
    #:x-register-dnd-atom
    ;; xsmfns.c
    #:handle-save-session
    ;;; 
    ))
