(defpackage :lice
  (:use :cl))

(labels ((cnl (file)
	   (compile-file file)
	      (load file)))
  (cnl "wrappers")
  (cnl "global")
  (cnl "major-mode")
  (cnl "buffer")
  (cnl "window")
  (cnl "frame")
  (cnl "clisp-render")
  (cnl "intervals")
  (cnl "textprop")
  (cnl "editfns")
  (cnl "input")
  (cnl "subr")
  (cnl "debugger")
  (cnl "recursive-edit")
  (cnl "minibuffer")
  (cnl "simple")
  (cnl "wm")
  (cnl "lisp-mode")
  (cnl "search")
  (cnl "syntax")
  (cnl "files")
  (cnl "main"))
